import { ControlDefinition, ProcedureType } from "@cirugias-cruz/domain";
import type { ProcedureTypeRepository } from "./procedure-type-repository.js";

export interface RegisterProcedureTypeInput {
  physicianId: string;
  id: string;
  name: string;
  description?: string;
  /**
   * Id for the default `ControlDefinition` seeded alongside this
   * ProcedureType (ADR 0030) — generated by the HTTP layer, same as
   * `id` above, so this operation never generates ids itself (this
   * package's established pattern; see `AddControlDefinitionInput`).
   */
  defaultControlDefinitionId: string;
}

export interface RegisterProcedureTypeOutput {
  procedureTypeId: string;
}

export interface RegisterProcedureTypeDeps {
  procedureTypeRepository: ProcedureTypeRepository;
}

/**
 * The label for the `ControlDefinition` every new ProcedureType is
 * seeded with (ADR 0030). Deliberately generic/non-clinical — it names
 * no pterygium-specific (or any specialty's) concept, the same
 * "platform ships no clinical content" posture as every other
 * structural default in this product (ADR 0011/0018/0022). The
 * physician can rename, retype, or remove it like any other definition.
 */
const DEFAULT_CONTROL_DEFINITION_NAME = "General";

/**
 * Registers a Procedure Type in the acting physician's tenant, and
 * (ADR 0030) seeds it with one default, uncapped `ControlDefinition` —
 * a `ProcedureType` is never left without at least one usable control
 * type, since `Control.definitionId` is now required (no ad-hoc
 * controls). Seeded atomically with the `ProcedureType` itself, in the
 * same `save()`, rather than as a second, separately-failable step.
 */
export function registerProcedureType(deps: RegisterProcedureTypeDeps) {
  return async function execute(
    input: RegisterProcedureTypeInput,
  ): Promise<RegisterProcedureTypeOutput> {
    const procedureType = ProcedureType.create({
      id: input.id,
      physicianId: input.physicianId,
      name: input.name,
      description: input.description,
    });

    const defaultControlDefinition = ControlDefinition.create({
      id: input.defaultControlDefinitionId,
      name: DEFAULT_CONTROL_DEFINITION_NAME,
      occurrenceRule: { mode: "uncapped" },
    });
    procedureType.addControlDefinition(defaultControlDefinition, input.physicianId);

    await deps.procedureTypeRepository.save(procedureType);

    return { procedureTypeId: procedureType.id };
  };
}
